[package]
name = "Auth"
version = "0.1.0"
edition = "2024"

[dependencies]

# -- Async
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
# -- Serde
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3"
# -- Web
axum = "0.8"
tower-http = { version = "0.6.6", features = ["fs"] }
tower-cookies = "0.11"
# -- Others
lazy-regex = "3"
strum_macros = "0.27"
uuid = {version = "1", features = ["v4","fast-rng",]}
derive_more = {version = "2", features = ["from", "display"] }
axum-server = "0.8.0"


[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"